layout_spectrum: 0.18478300119750202
typography_spectrum: 0.569374566199258
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#c7c7c7'
    - '#474747'
    - '#7f7f7f'
  brandStrength: 0.1553648989647627
  lightness: 0.08810741128399968
  saturation: 0.5623390632681549
  rhythmicContrast: 0.8729635807685554
coverPrefs:
  filter: false
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: UA-64940557-1
  facebook: null
  twitter: null
author:
  name: Nuno Santos
  email: nooneswork@gmail.com
  url: noonestuff.xyz
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/bd9ebae8-1006-4614-8590-6632bdf8fe03.jpg
name: Noone'stuff
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ff71e09b-c332-4a8d-9e32-3c0b53aaaa50.png
title: null
purpose: []
