name: Noone'stuff
favicon: null
layout_spectrum: 1
typography_spectrum: 0.60411
title: Noone'stuff
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-64940557-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#474747'
    - '#ffffff'
    - '#7a0001'
    - '#a3a3a3'
  brandStrength: 0.5
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
