name: Noone'stuff
favicon: null
layout_spectrum: 1
typography_spectrum: 0.60411
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-64940557-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#266e63'
    - '#f13627'
    - '#e79a88'
    - '#fdfdfd'
  brandStrength: 0.5
  lightness: 0.125
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
